version: "3.1"

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "3306:5432"

    container_name: nest_api_db

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sm

    volumes:
      - /var/lib/postgresql/data
